// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPacket

import "strconv"

type ChatType int8

const (
	ChatTypeCHAT    ChatType = 0
	ChatTypeWHISPER ChatType = 1
	ChatTypeSYSTEM  ChatType = 2
)

var EnumNamesChatType = map[ChatType]string{
	ChatTypeCHAT:    "CHAT",
	ChatTypeWHISPER: "WHISPER",
	ChatTypeSYSTEM:  "SYSTEM",
}

var EnumValuesChatType = map[string]ChatType{
	"CHAT":    ChatTypeCHAT,
	"WHISPER": ChatTypeWHISPER,
	"SYSTEM":  ChatTypeSYSTEM,
}

func (v ChatType) String() string {
	if s, ok := EnumNamesChatType[v]; ok {
		return s
	}
	return "ChatType(" + strconv.FormatInt(int64(v), 10) + ")"
}
